// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Article: typeof import('./src/components/article/Article.vue')['default']
    ArticlePreview: typeof import('./src/components/article/ArticlePreview.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    TopHeader: typeof import('./src/components/top-header/TopHeader.vue')['default']
    User: typeof import('./src/components/user/User.vue')['default']
  }
}

export { }
